graph [
  directed 0
  node [ id 0 label "Atlanta" ]
  node [ id 1 label "Chicago" ]
  node [ id 2 label "Denver" ]
  node [ id 3 label "Houston" ]
  node [ id 4 label "Indianapolis" ]
  node [ id 5 label "Kansas City" ]
  node [ id 6 label "Los Angeles" ]
  node [ id 7 label "New York" ]
  node [ id 8 label "Salt Lake City" ]
  node [ id 9 label "San Francisco" ]
  node [ id 10 label "Seattle" ]
  node [ id 11 label "Washington" ]
  edge [ source 0 target 3 ]
  edge [ source 0 target 4 ]
  edge [ source 0 target 7 ]
  edge [ source 1 target 4 ]
  edge [ source 1 target 5 ]
  edge [ source 1 target 7 ]
  edge [ source 2 target 5 ]
  edge [ source 2 target 8 ]
  edge [ source 3 target 5 ]
  edge [ source 4 target 5 ]
  edge [ source 5 target 8 ]
  edge [ source 6 target 9 ]
  edge [ source 6 target 10 ]
  edge [ source 6 target 8 ]
  edge [ source 7 target 11 ]
  edge [ source 8 target 10 ]
  edge [ source 9 target 10 ]
  edge [ source 11 target 7 ]
]